plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: Scylla Sequence
description: The Most Boring Blog
lang: en
locale: en_GB
url: "https://www.scyllasequence.com"
baseurl: ""

# RSS feeds
feed:
  posts_limit: 20
